const fs = require('fs');
const util = require('util')

// Carrega o automerge no node
const Automerge = require('automerge')

// Inicializamos o documento para conter inicialmente uma lista vazia de cards. 
//let Doc = Automerge.from({ cards: [] })

let Doc = Automerge.from({cards:[

{done:true,"title":"P2P networking is..."},
{done:false,"title":"In its simplest form, a peer-to-peer (P2P) network is created when two or more PCs are connected and share resources without going through a separate server computer. A P2P network can be an ad hoc connection—a couple of computers connected via a Universal Serial Bus to transfer files. A P2P network also can be a permanent infrastructure that links a half-dozen computers in a small office over copper wires. Or a P2P network can be a network on a much grander scale in which special protocols and applications set up direct relationships among users over the Internet."},
{done:false,"title":"The initial use of P2P networks in business followed the deployment in the early 1980s of free-standing PCs. In contrast to the minimainframes of the day, such as the VS system from Wang Laboratories Inc., which served up word processing and other applications to dumb terminals from a central computer and stored files on a central hard drive, the then-new PCs had self-contained hard drives and built-in CPUs. The smart boxes also had onboard applications, which meant they could be deployed to desktops and be useful without an umbilical cord linking them to a mainframe."},
{done:false,"title":"Many workers felt liberated by having dedicated PCs on their desktops. But soon they needed a way to share files and printers. The obvious solution was to save files to a floppy disk and carry the disk to the intended recipient or send it by interoffice mail"},
{done:false,"title":"That practice resulted in the term sneaker net. The most frequent endpoint of a typical sneaker net was the worker who had a printer connected to his machine.While sneaker nets seemed an odd mix of the newest technology and the oldest form of transportation, the model is really the basis for today's small P2P workgroups. Whereas earlier centralized computing models and today's client/server systems are generally considered controlled environments in which individuals use their PCs in ways determined by a higher authority, a classic P2P workgroup network is all about openly sharing files and devices. In general, office and home P2P networks operate over Ethernet (10M bit/sec.) or Fast Ethernet (100M bit/sec.) and employ a hub-and-spoke topology. Category 5 (twisted-pair) copper wire runs among the PCs and an Ethernet hub or switch, enabling users of those networked PCs access to one another's hard drives, printers or perhaps a shared Internet connection."},
{done:false,"title":"In effect, every connected PC is at once a server and a client. There's no special network operating system residing on a robust machine that supports special server-side applications like directory services specialized databases that control who has access to what. In a P2P environment, access rights are governed by setting sharing permissions on individual machines. For example, if User A's PC is connected to a printer that User B wants to access, User A must set his machine to allow - share - access to the printer. Similarly, if User B wants to have access to a folder or file, or even a complete hard drive, on User A's PC, User A must enable file sharing on his PC. Access to folders and printers on an office P2P network can be further controlled by assigning passwords to those resources."},

{done:false,"title":"In its simplest form, a peer-to-peer (P2P) network is created when two or more PCs are connected and share resources without going through a separate server computer. A P2P network can be an ad hoc connection—a couple of computers connected via a Universal Serial Bus to transfer files. A P2P network also can be a permanent infrastructure that links a half-dozen computers in a small office over copper wires. Or a P2P network can be a network on a much grander scale in which special protocols and applications set up direct relationships among users over the Internet."},
{done:false,"title":"The initial use of P2P networks in business followed the deployment in the early 1980s of free-standing PCs. In contrast to the minimainframes of the day, such as the VS system from Wang Laboratories Inc., which served up word processing and other applications to dumb terminals from a central computer and stored files on a central hard drive, the then-new PCs had self-contained hard drives and built-in CPUs. The smart boxes also had onboard applications, which meant they could be deployed to desktops and be useful without an umbilical cord linking them to a mainframe."},
{done:false,"title":"Many workers felt liberated by having dedicated PCs on their desktops. But soon they needed a way to share files and printers. The obvious solution was to save files to a floppy disk and carry the disk to the intended recipient or send it by interoffice mail"},
{done:false,"title":"That practice resulted in the term sneaker net. The most frequent endpoint of a typical sneaker net was the worker who had a printer connected to his machine.While sneaker nets seemed an odd mix of the newest technology and the oldest form of transportation, the model is really the basis for today's small P2P workgroups. Whereas earlier centralized computing models and today's client/server systems are generally considered controlled environments in which individuals use their PCs in ways determined by a higher authority, a classic P2P workgroup network is all about openly sharing files and devices. In general, office and home P2P networks operate over Ethernet (10M bit/sec.) or Fast Ethernet (100M bit/sec.) and employ a hub-and-spoke topology. Category 5 (twisted-pair) copper wire runs among the PCs and an Ethernet hub or switch, enabling users of those networked PCs access to one another's hard drives, printers or perhaps a shared Internet connection."},
{done:false,"title":"In effect, every connected PC is at once a server and a client. There's no special network operating system residing on a robust machine that supports special server-side applications like directory services specialized databases that control who has access to what. In a P2P environment, access rights are governed by setting sharing permissions on individual machines. For example, if User A's PC is connected to a printer that User B wants to access, User A must set his machine to allow - share - access to the printer. Similarly, if User B wants to have access to a folder or file, or even a complete hard drive, on User A's PC, User A must enable file sharing on his PC. Access to folders and printers on an office P2P network can be further controlled by assigning passwords to those resources."},

{done:false,"title":"In its simplest form, a peer-to-peer (P2P) network is created when two or more PCs are connected and share resources without going through a separate server computer. A P2P network can be an ad hoc connection—a couple of computers connected via a Universal Serial Bus to transfer files. A P2P network also can be a permanent infrastructure that links a half-dozen computers in a small office over copper wires. Or a P2P network can be a network on a much grander scale in which special protocols and applications set up direct relationships among users over the Internet."},
{done:false,"title":"The initial use of P2P networks in business followed the deployment in the early 1980s of free-standing PCs. In contrast to the minimainframes of the day, such as the VS system from Wang Laboratories Inc., which served up word processing and other applications to dumb terminals from a central computer and stored files on a central hard drive, the then-new PCs had self-contained hard drives and built-in CPUs. The smart boxes also had onboard applications, which meant they could be deployed to desktops and be useful without an umbilical cord linking them to a mainframe."},
{done:false,"title":"Many workers felt liberated by having dedicated PCs on their desktops. But soon they needed a way to share files and printers. The obvious solution was to save files to a floppy disk and carry the disk to the intended recipient or send it by interoffice mail"},
{done:false,"title":"That practice resulted in the term sneaker net. The most frequent endpoint of a typical sneaker net was the worker who had a printer connected to his machine.While sneaker nets seemed an odd mix of the newest technology and the oldest form of transportation, the model is really the basis for today's small P2P workgroups. Whereas earlier centralized computing models and today's client/server systems are generally considered controlled environments in which individuals use their PCs in ways determined by a higher authority, a classic P2P workgroup network is all about openly sharing files and devices. In general, office and home P2P networks operate over Ethernet (10M bit/sec.) or Fast Ethernet (100M bit/sec.) and employ a hub-and-spoke topology. Category 5 (twisted-pair) copper wire runs among the PCs and an Ethernet hub or switch, enabling users of those networked PCs access to one another's hard drives, printers or perhaps a shared Internet connection."},
{done:false,"title":"In effect, every connected PC is at once a server and a client. There's no special network operating system residing on a robust machine that supports special server-side applications like directory services specialized databases that control who has access to what. In a P2P environment, access rights are governed by setting sharing permissions on individual machines. For example, if User A's PC is connected to a printer that User B wants to access, User A must set his machine to allow - share - access to the printer. Similarly, if User B wants to have access to a folder or file, or even a complete hard drive, on User A's PC, User A must enable file sharing on his PC. Access to folders and printers on an office P2P network can be further controlled by assigning passwords to those resources."},

{done:false,"title":"In its simplest form, a peer-to-peer (P2P) network is created when two or more PCs are connected and share resources without going through a separate server computer. A P2P network can be an ad hoc connection—a couple of computers connected via a Universal Serial Bus to transfer files. A P2P network also can be a permanent infrastructure that links a half-dozen computers in a small office over copper wires. Or a P2P network can be a network on a much grander scale in which special protocols and applications set up direct relationships among users over the Internet."},
{done:false,"title":"The initial use of P2P networks in business followed the deployment in the early 1980s of free-standing PCs. In contrast to the minimainframes of the day, such as the VS system from Wang Laboratories Inc., which served up word processing and other applications to dumb terminals from a central computer and stored files on a central hard drive, the then-new PCs had self-contained hard drives and built-in CPUs. The smart boxes also had onboard applications, which meant they could be deployed to desktops and be useful without an umbilical cord linking them to a mainframe."},


]});

console.log("Documento original do passo 1\n ",Doc);

// Salva o arquivo local .automerge com os metadados automerge do json
fs.writeFileSync("file1.automerge", Automerge.save(Doc), {encoding: null}); 
		
// Salva o arquivo local .json
fs.writeFileSync("file1.json", JSON.stringify(Doc), {encoding: null}); 
console.log("Documento original do passo 1 salvo em disco!\n ");


